# Generated by Django 5.2.8 on 2025-11-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'Can view'), ('can_create', 'Can create'), ('can_delete', 'Can delete'), ('can_edit', 'Can edit')]},
        ),
    ]
